title = "06-nfsr3"
author = "huangx607087"
difficulty = "Medium"
flag = "susctf{[GUID]}"

description = """

[ç¾¤èŠ] SUS Crypto å‡ºé¢˜è®¨è®º (10)

longque: å†å‡ºä¸€ä¸ªçŒœæ•°å­—çš„é¢˜ï¼ŒçŒœå¯¹1000æ¬¡ç»™flag ğŸ

huangx607087: é‚£ä¹Ÿå¤ªç›´æ¥äº† ğŸ¤”ï¼Œå¹¶ä¸”äº¤äº’ 1000 æ¬¡ï¼Œæ˜¯ä¸æ˜¯æœ‰ç‚¹å¤šäº†ï¼Ÿ

MaPl: ä¸¤ä¸ªéšæœºæ•°äº§ç”Ÿå™¨å¼‚æˆ–ä¸€ä¸‹ä¸å°±è¡Œäº†å—ï¼ŸğŸ˜

huangx607087: ğŸ¤“ğŸ‘† å¥½äº†æˆ‘çŸ¥é“è¯¥æ€ä¹ˆå‡ºäº†ã€‚

"""

[container]
port = 9999
cpu = 3 # 0.1*1ä¸ªcpu
memory = 160 # unit: MiB
storage = 400 # unit: MiB **æ³¨æ„ï¼šåŒ…å«é•œåƒå¤§å°**

[attachments]
path = ["build/src/task.py"]
